// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SucessoEventos.Entities;

#nullable disable

namespace SucessoEventos.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240915200840_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SucessoEventos.Entities.Atividade", b =>
                {
                    b.Property<int>("CodAtv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodAtv"));

                    b.Property<string>("DescAtv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Vagas")
                        .HasColumnType("int");

                    b.HasKey("CodAtv");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("SucessoEventos.Entities.AxParticipanteAtividade", b =>
                {
                    b.Property<int>("CodPar")
                        .HasColumnType("int");

                    b.Property<int>("CodAtv")
                        .HasColumnType("int");

                    b.Property<int?>("ParticipanteCodPar")
                        .HasColumnType("int");

                    b.HasKey("CodPar", "CodAtv");

                    b.HasIndex("CodAtv");

                    b.HasIndex("ParticipanteCodPar");

                    b.ToTable("AxParticipanteAtividade");
                });

            modelBuilder.Entity("SucessoEventos.Entities.AxParticipantePacote", b =>
                {
                    b.Property<int>("CodPar")
                        .HasColumnType("int");

                    b.Property<int>("CodPacote")
                        .HasColumnType("int");

                    b.HasKey("CodPar", "CodPacote");

                    b.HasIndex("CodPacote");

                    b.ToTable("AxParticipantePacote");
                });

            modelBuilder.Entity("SucessoEventos.Entities.Pacote", b =>
                {
                    b.Property<int>("CodPacote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodPacote"));

                    b.Property<DateTime>("DataViradaPreco")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("CodPacote");

                    b.ToTable("Pacotes");
                });

            modelBuilder.Entity("SucessoEventos.Entities.Participante", b =>
                {
                    b.Property<int>("CodPar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodPar"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CodPar");

                    b.ToTable("Participantes", (string)null);
                });

            modelBuilder.Entity("SucessoEventos.Entities.AxParticipanteAtividade", b =>
                {
                    b.HasOne("SucessoEventos.Entities.Atividade", "Atividade")
                        .WithMany()
                        .HasForeignKey("CodAtv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SucessoEventos.Entities.Participante", "Participante")
                        .WithMany()
                        .HasForeignKey("CodPar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SucessoEventos.Entities.Participante", null)
                        .WithMany("AxParticipanteAtividades")
                        .HasForeignKey("ParticipanteCodPar");

                    b.Navigation("Atividade");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("SucessoEventos.Entities.AxParticipantePacote", b =>
                {
                    b.HasOne("SucessoEventos.Entities.Pacote", "Pacote")
                        .WithMany("AxParticipantePacotes")
                        .HasForeignKey("CodPacote")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SucessoEventos.Entities.Participante", "Participante")
                        .WithMany("AxParticipantePacotes")
                        .HasForeignKey("CodPar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacote");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("SucessoEventos.Entities.Pacote", b =>
                {
                    b.Navigation("AxParticipantePacotes");
                });

            modelBuilder.Entity("SucessoEventos.Entities.Participante", b =>
                {
                    b.Navigation("AxParticipanteAtividades");

                    b.Navigation("AxParticipantePacotes");
                });
#pragma warning restore 612, 618
        }
    }
}
